---
on: [push, pull_request]
name: Integration tests

jobs:
  integration-tests:
    uses: coreruleset/crs-plugin-test-action/.github/workflows/integration.yaml@81cb7f29881911c56f33a82d1e25dc26e0e13636 # v3.0.2
