---
name: Integration/Regression

on: [push, pull_request]

jobs:
  modsecurity-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v2

      - name: "Install dependencies"
        run: |
          wget https://github.com/coreruleset/coreruleset/archive/refs/tags/nightly.tar.gz -O /tmp/nightly.tar.gz
          tar -zxvf /tmp/nightly.tar.gz -C /tmp/
          curl -skLo - https://github.com/coreruleset/go-ftw/releases/latest/download/ftw_Linux_x86_64.tar.gz | tar -xzf - ftw
      
      - name: "Test plugin on ModSecurity v2 / Apache"
        run: |
          touch plugins/placeholder-config.conf
          touch plugins/placeholder-before.conf
          touch plugins/placeholder-after.conf

          docker-compose -f tests/integration/docker-compose.yml --project-directory . up -d apache-nightly
          echo "waiting for the webserver to start"; sleep 10

          ./ftw check -d tests/regression/tests
          ./ftw run -d tests/regression/tests

          docker-compose -f tests/integration/docker-compose.yml --project-directory . down
        env:
          FTW_LOGFILE: './tests/logs/modsec2-apache/error.log'
          FTW_LOGTYPE_NAME: 'apache'
          FTW_LOGTYPE_TIMEREGEX: '\[([A-Z][a-z]{2} [A-z][a-z]{2} \d{1,2} \d{1,2}\:\d{1,2}\:\d{1,2}\.\d+? \d{4})\]'
          FTW_LOGTYPE_TIMEFORMAT: 'ddd MMM DD HH:mm:ss.S YYYY'
      
      - name: "Test plugin on ModSecurity v3 / Nginx"
        # test on Nginx temp disabled
        #if: ${{ false }}
        run: |
          touch plugins/placeholder-config.conf
          touch plugins/placeholder-before.conf
          touch plugins/placeholder-after.conf

          docker-compose -f tests/integration/docker-compose.yml --project-directory . up -d nginx-nightly
          echo "waiting for the webserver to start"; sleep 10

          docker cp tests/integration/modsec-setup.conf nginx-nightly:/etc/modsecurity.d/setup.conf
          cat << EOF > /tmp/crs-setup.conf
          SecDefaultAction "phase:1,pass,log,tag:'modsecurity'"\nSecDefaultAction "phase:2,pass,log,tag:'modsecurity'"
          SecAction "id:900000,phase:1,nolog,pass,t:none,setvar:tx.blocking_paranoia_level=4"
          SecAction "id:900110,phase:1,nolog,pass,t:none,setvar:tx.inbound_anomaly_score_threshold=5,setvar:tx.outbound_anomaly_score_threshold=4"
          SecAction "id:900350,phase:1,nolog,pass,t:none,setvar:tx.combined_file_sizes=65535"
          SecCollectionTimeout 600
          SecAction "id:900990,phase:1,nolog,pass,t:none,setvar:tx.crs_setup_version=400"
          SecRule REQUEST_HEADERS:X-CRS-Test "@rx ^.*$" "id:999999,phase:1,log,msg:'%{MATCHED_VAR}',pass,t:none"
          EOF
          docker cp /tmp/crs-setup.conf nginx-nightly:/etc/modsecurity.d/owasp-crs/crs-setup.conf
          docker exec nginx-nightly nginx -s reload

          echo "waiting nginx reload"; sleep 5

          ./ftw check -d tests/regression/tests
          ./ftw run -d tests/regression/tests

          docker-compose -f tests/integration/docker-compose.yml --project-directory . down
        env:
          FTW_LOGFILE: './tests/logs/modsec3-nginx/error.log'
          FTW_LOGTYPE_NAME: 'apache'
          FTW_LOGTYPE_TIMEREGEX: '\[([A-Z][a-z]{2} [A-z][a-z]{2} \d{1,2} \d{1,2}\:\d{1,2}\:\d{1,2}\.\d+? \d{4})\]'
          FTW_LOGTYPE_TIMEFORMAT: 'ddd MMM DD HH:mm:ss.S YYYY'
